packages:
  - examples/*
  - package
  - plugin
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.10.1+sha512-qLbAWHXszOBaSUPiTpV2qsfVA1phj/ferkbsZvd3aA3QhcfuTwATayqFfABfNmK5saTC6KhfAUxEsrAPRW7tDw==
loglevel: info
